vim.g.mapleader = " "
vim.g.maplocalleader = "\\"
require("config.autocmds")
require("config.autopairs")
require("config.bufferline")
require("config.cmp")
require("config.conform")
require("config.crates")
require("config.gitsigns")
require("config.indentblankline")
require("config.kanagawa")
require("config.keymaps")
require("config.lspconfig")
require("config.lsplines")
require("config.lualine")
require("config.options")
require("config.telescope")
require("config.treesitter")
require("config.undotree")
require("config.obsidian")
require("config.rendermarkdown")
require("config.vim-tmux-navigator")
