vim.g.mapleader = " "
vim.g.maplocalleader = "\\"
require("config.autocmds")
require("config.options")
require("config.keymaps")
require("plugins.bufferline")
require("plugins.cmp")
require("plugins.conform")
require("plugins.crates")
require("plugins.gitsigns")
require("plugins.indentblankline")
require("plugins.kanagawa")
require("plugins.lspconfig")
require("plugins.lsplines")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.undotree")
-- require("plugins.obsidian")
require("plugins.rendermarkdown")
require("plugins.tmuxnavigator")
